In [1]:
import torch
print(torch.__version__)

2.3.0+cu121


## Tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# checking the dimension of scalar
scalar.ndim

0

In [4]:
# get tensor back as int, .item can only be used to access scalar items from tensor
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([3,3,3])
vector


tensor([3, 3, 3])

In [6]:
#Checking the dimension of the vector. We can tell the dimension by seeing the number of Large brackets in the tensor
vector.ndim

1

In [7]:
# Shape is 3*1. The result is the number of elements in the tensor
vector.shape

torch.Size([3])

In [8]:
# MATRIX
MATRIX = torch.tensor([[1,1],
                      [2,2]])
MATRIX

tensor([[1, 1],
        [2, 2]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# the indexing starts from 0
MATRIX[0], MATRIX[1]

(tensor([1, 1]), tensor([2, 2]))

In [12]:
# Tensor
TENSOR = torch.tensor([[[[1,1,1,1],
                         [2,2,2,2],
                         [3,3,3,2]],
                        [[3,3,3,3],
                         [4,4,4,3],
                         [5,5,5,5]]]])
TENSOR

tensor([[[[1, 1, 1, 1],
          [2, 2, 2, 2],
          [3, 3, 3, 2]],

         [[3, 3, 3, 3],
          [4, 4, 4, 3],
          [5, 5, 5, 5]]]])

In [13]:
TENSOR.ndim

4

In [14]:
TENSOR.shape

torch.Size([1, 2, 3, 4])

In [15]:
TENSOR[0,1,2]

tensor([5, 5, 5, 5])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust random numbers to better represent the data.

`Satrt with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [16]:
# creating random tensor
random_tensor = torch.rand(3,4) #torch.rand generates number in the interval [0,1)
random_tensor

tensor([[0.6832, 0.9520, 0.7455, 0.4134],
        [0.8461, 0.8466, 0.3165, 0.7188],
        [0.1634, 0.9766, 0.7583, 0.4656]])

In [58]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(3, 224, 224) # we can also use the syntax torch.rand(size = (3, 224, 224)). (224, 224, 3) can respectively represent the colour channels, height and width of the image
random_image_size_tensor.shape, random_image_size_tensor.ndim, random_image_size_tensor

(torch.Size([3, 224, 224]),
 3,
 tensor([[[0.8694, 0.5677, 0.7411,  ..., 0.9208, 0.7619, 0.6265],
          [0.4951, 0.1197, 0.0716,  ..., 0.9613, 0.5715, 0.2050],
          [0.4717, 0.6201, 0.6751,  ..., 0.5697, 0.2088, 0.6539],
          ...,
          [0.7133, 0.8727, 0.4658,  ..., 0.5227, 0.3914, 0.9721],
          [0.8717, 0.8864, 0.4770,  ..., 0.2318, 0.4865, 0.0602],
          [0.7150, 0.2971, 0.6150,  ..., 0.1209, 0.2951, 0.0345]],
 
         [[0.8077, 0.5241, 0.2698,  ..., 0.4076, 0.8279, 0.4652],
          [0.7432, 0.7510, 0.0291,  ..., 0.1677, 0.4922, 0.7635],
          [0.4994, 0.0296, 0.4289,  ..., 0.6203, 0.9258, 0.6213],
          ...,
          [0.5948, 0.7264, 0.9969,  ..., 0.4678, 0.9012, 0.4214],
          [0.1502, 0.1897, 0.8450,  ..., 0.2476, 0.8822, 0.0417],
          [0.4815, 0.6314, 0.1022,  ..., 0.4162, 0.4793, 0.9740]],
 
         [[0.7056, 0.0741, 0.2354,  ..., 0.1421, 0.0470, 0.7302],
          [0.2395, 0.3808, 0.0730,  ..., 0.4830, 0.8793, 0.6624],
        

###Zeros and Ones

In [18]:
# create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
# create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
# float32 is the default datatype of tensor
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [22]:
# the end point is not included in torch.arange(). We should avoid using torch.range because it is deprecated and will be removed in the future
tensor_using_arange = torch.arange(1,11,2) #start stop step
tensor_using_arange

tensor([1, 3, 5, 7, 9])

In [23]:
# default int datatype is int64. torch.arange has datatype of int64
tensor_using_arange.dtype

torch.int64

In [24]:
five_zeros = torch.zeros_like(tensor_using_arange)
five_zeros

tensor([0, 0, 0, 0, 0])

## Tensor datatypes

Note: Some of the 3 big errors that we may run into with PyTorch and deeplearning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [25]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor?
                               device = "cpu", # by default the device is cpu, "cuda" is for GPU
                               requires_grad = False) # whether or not to track the gradients of this tensor
float_32_tensor

tensor([3., 6., 9.])

In [26]:
# float32 is the default float datatype for tensor
float_32_tensor.dtype

torch.float32

In [27]:
# method to change the datatype of the tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [28]:
# multiplication automatically changes to higher bit dtype, sometimes different datatypes gives mismatched datatypes errors
float_multiplication = float_16_tensor * float_32_tensor
float_multiplication

tensor([ 9., 36., 81.])

In [29]:
float_multiplication.dtype

torch.float32

## Manipulating Tensors (Tensor operations)

Tensor operations include:

* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [30]:
# Cretae a tensor and add 10 to it

tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [31]:
# Multiply tensor by 10
tensor *= 10
tensor

tensor([10, 20, 30])

In [32]:
# Try PyTorch in-built functions
torch.mul(5,tensor)

tensor([ 50, 100, 150])

 ## Finding the min, max, mean, sum, etc (tensor aggregations)

In [33]:
tensor = torch.arange(0,100,10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
# finding the minimum of the tensor
torch.min(tensor), tensor.min()

(tensor(0), tensor(0))

In [35]:
# finding the max of the tensor
torch.max(tensor), tensor.max()

(tensor(90), tensor(90))

In [36]:
# finding mean of the tensor. The torch.mean function takes only float32 as the parameter
torch.mean(tensor.type(torch.float32))

tensor(45.)

## Finding the positional min and max

In [37]:
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
#Find the position in the tensor that has the minimum value, returns the index of the minimum value in the tensor
tensor.argmin()

tensor(0)

In [39]:
#Find the position in the tensor that has the maximum value, returns the index of the maximum value in the tensor
tensor.argmax()

tensor(9)

 ## Reshaping, stacking, squeezing and unsqueezing tensors

 * Reshaping - reshapes an input tensor to a defined shape
 * View - Return a view of an inut tensorr of certain shape but keep the same memory as the original tensor
 * Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
 * Squeeze - removes all `1` dimensions from a tensor
 * Unsqueeze - add a `1` dimension to a target tensor
 * Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [40]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [41]:
# Reshaping
x_reshaped = x.reshape(3,3)
x_reshaped, x_reshaped.shape #The final reshaped size should be compatible with the original tensor

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [42]:
 # Change the view
 z = x.view(1, 9)
 z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [43]:
# Changing z changes x because a view of a tensor shares the same memory as the original tensor
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [44]:
y = torch.arange(1.,19., 2)
y

tensor([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17.])

In [45]:
x_stacked = torch.stack([x,x,x,y], dim = 0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17.]])

In [46]:
x_stacked = torch.stack([x,x,x,y], dim = 1)
x_stacked

tensor([[ 5.,  5.,  5.,  1.],
        [ 2.,  2.,  2.,  3.],
        [ 3.,  3.,  3.,  5.],
        [ 4.,  4.,  4.,  7.],
        [ 5.,  5.,  5.,  9.],
        [ 6.,  6.,  6., 11.],
        [ 7.,  7.,  7., 13.],
        [ 8.,  8.,  8., 15.],
        [ 9.,  9.,  9., 17.]])

In [47]:
# Squeeze tensor
zeros = torch.zeros(2,1,2,3,1)
zeros, zeros.shape

(tensor([[[[[0.],
            [0.],
            [0.]],
 
           [[0.],
            [0.],
            [0.]]]],
 
 
 
         [[[[0.],
            [0.],
            [0.]],
 
           [[0.],
            [0.],
            [0.]]]]]),
 torch.Size([2, 1, 2, 3, 1]))

In [48]:
zeros.squeeze().shape # removes all the single dimensions from the tensor

torch.Size([2, 2, 3])

 ## PyTorch and Numpy
* Data in NumPy, wnat in Pytorch Tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `tensor.numpy()`


In [49]:
import numpy as np

array = np.arange(1., 8.)
tensor = torch.from_numpy(array) # to change to float32 we can use .type(torch.float32) at last
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [50]:
array.dtype # the default datatype for numpy is float64 but the default datatypep for pytorch is float32

dtype('float64')

In [51]:
tensor.dtype # we get float64 because the default dtype for numpy is float64

torch.float64

In [52]:
# Tensor to numpy
tensor = torch.arange(1.,9.)
array2 = tensor.numpy()
array2.dtype, tensor

(dtype('float32'), tensor([1., 2., 3., 4., 5., 6., 7., 8.]))

## Reproducibility (Taking random out of the randomness)


In [53]:
# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_A = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) # we should use torch.manual_seed everytime
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A == random_tensor_B)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs

## Check for GPU access with PyTorch

In [54]:
import torch
torch.cuda.is_available()

False

In [55]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [56]:
torch.cuda.device_count()

0